[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "0.8.7"

[[constraint]]
  name = "github.com/fatih/color"
  version = "0.1.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
name = "github.com/pkg/term"
branch = "master"

